[package]
name = "pepeeltoro41/pepecs"
version = "0.0.2"
description = "Pepecs: an ecs"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = [
    "default.project.json",
    "src",
    "src/**",
    "wally.toml",
    "README.md",
    "LICENSE",
]
exclude = ["**"]
